Issue 6 implement forgot password api
zinza-academy/covid-19-vaccine-portal-nestjs-dnv pull request #12
Opened 2024-04-16 03:07 UTC by NguyenDonUET

2024-04-16 03:40 UTC, hungnp194 requested changes

2024-04-16 03:40 UTC, hungnp194 commented on src/modules/auth/auth.service.ts
> +    const resetToken = this.generateResetPasswordToken(payload);
Lưu lại resetToken, 1 resetToken chỉ được dùng 1 lần

2024-04-16 03:40 UTC, hungnp194 commented on src/modules/auth/auth.service.ts
> +    }
Check reset token đã được dùng chưa?

2024-04-17 03:34 UTC, hungnp-zinza approved these changes

2024-04-17 03:35 UTC, hungnp194 approved these changes

2024-04-17 03:35 UTC, merged